### ISSUE TITLE
Duplicate License 

### ISSUE THREAD

**Issue by rgocal** [jahirfiquitiva/Tap-Issues-Tracker#14]
You have 2 Material Intro licenses 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3</td></tr>
<tr><td>App version code</td><td>13</td></tr>
<tr><td>Android build version</td><td>844935.5</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M release-keys</td></tr>
<tr><td>Device brand</td><td>htc</td></tr>
<tr><td>Device manufacturer</td><td>HTC</td></tr>
<tr><td>Device name</td><td>htc_pmewl</td></tr>
<tr><td>Device model</td><td>HTC 10</td></tr>
<tr><td>Device product name</td><td>pmewl_00531</td></tr>
<tr><td>Device hardware name</td><td>htc_pme</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>App</td><td>Tap for Keep</td></tr>
</table>

**Comment by jahirfiquitiva** [comment]
Thanks for letting me know. Just fixed it. Will push an update asap.
