### ISSUE TITLE

Can't scroll in main menu

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/Tap-Issues-Tracker#5]
I've set a very large font size and high DPI. I can't scroll the main menu (and therefore I can't access some items) but I can see the scroll bar.

-

Device info:
---
<table>
<tr><td>App version</td><td>1.0</td></tr>
<tr><td>App version code</td><td>1</td></tr>
<tr><td>Android build version</td><td>9fb1a6a5bb</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>OnePlus2-userdebug 7.1.1 NMF26V 9fb1a6a5bb test-keys</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus2</td></tr>
<tr><td>Device model</td><td>ONE A2003</td></tr>
<tr><td>Device product name</td><td>OnePlus2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by timoschwarzer** [comment]
May be related to #5
