### ISSUE TITLE
Queep launcher bubble doesnt launch new notes

### ISSUE THREAD

**Issue by scionwest** [jahirfiquitiva/Tap-Issues-Tracker#9]
When i touch tge queep launcher bubble, norhing happens. Tge icon flashes, indicating it was touched; nothing happens though. I can use tge Create a Note button in the notification drawer without issue. 

-

Device info:
---
<table>
<tr><td>App version</td><td>1.1</td></tr>
<tr><td>App version code</td><td>11</td></tr>
<tr><td>Android build version</td><td>3514931</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26O</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>marlin</td></tr>
<tr><td>Device model</td><td>Pixel XL</td></tr>
<tr><td>Device product name</td><td>marlin</td></tr>
<tr><td>Device hardware name</td><td>marlin</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by jahirfiquitiva** [comment]
Sorry, but I'm not able to reproduce it. Can you share a video, or be more detailed in description? Thanks

**Comment by scionwest** [comment]
You can see it happening in this video https://youtu.be/CoyRTizM5ws

**Comment by scionwest** [comment]
I tap all over and it finally loaded. But then after closing I tap all over again and nothing happens. I'm not sure what caused it to load after a bunch of taps, but it's really sporadic

**Comment by jahirfiquitiva** [comment]
@scionwest
Thanks for the video and the info. I will give a look at it and try to fix it asap. Sorry for the inconvenience.

**Comment by jahirfiquitiva** [comment]
@scionwest
Can you try the latest version?

**Comment by scionwest** [comment]
Works for me now, thanks!

**Comment by jahirfiquitiva** [comment]
Awesome 😀
